export SHELL=$(which zsh)
export LANG=fr_FR.UTF-8
export LANGUAGE=
export LC_CTYPE="fr_FR.UTF-8"
export LC_NUMERIC="fr_FR.UTF-8"
export LC_TIME="fr_FR.UTF-8"
export LC_COLLATE="fr_FR.UTF-8"
export LC_MONETARY="fr_FR.UTF-8"
export LC_MESSAGES="fr_FR.UTF-8"
export LC_PAPER="fr_FR.UTF-8"
export LC_NAME="fr_FR.UTF-8"
export LC_ADDRESS="fr_FR.UTF-8"
export LC_TELEPHONE="fr_FR.UTF-8"
export LC_MEASUREMENT="fr_FR.UTF-8"
export LC_IDENTIFICATION="fr_FR.UTF-8"
export LC_ALL=C
systcl fs.protected_fifos=2
sysctl dev.tty.ldisc_autoload=0
sysctl fs.protected_regular=2
sysctl fs.suid_dumpable=0
sysctl kernel.kptr_restrict=2
sysctl kernel.modules_disabled=1
sysctl kernel.perf_event_paranoid=3
sysctl kernel.sysrq=0
sysctl kernel.unprivileged_bpf_disabled=1
sysctl net.core.bpf_jit_harden=2
# sysctl net.ipv4.conf.all.accept_redirects=0
# sysctl net.ipv4.conf.all.log_martians=1
# sysctl net.ipv4.conf.all.rp_filter=1
# sysctl net.ipv4.conf.all.send_redirects=0
# sysctl net.ipv4.conf.default.accept_redirects=0
# sysctl net.ipv4.conf.default.log_martians=1
# sysctl net.ipv6.conf.all.accept_redirects=0
# sysctl net.ipv6.conf.default.accept_redirects=0
pulseaudio --start
startx
